import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Navbar from "@/app/components/navigation/Navbar";
import { ThemeProvider } from "@/app/components/theme-provider";

import {
  TooltipProvider,
} from "@/app/components/ui/tooltip"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Renz Glorioso",
  description: "Generated by create next app",
  icons: "/icons/favicon.ico"

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={GeistSans.className} >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TooltipProvider>
              <Navbar />
              {children}
            </TooltipProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
